services:
  app:
    build:
      context: ./docker/php
    container_name: shadibari-app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: shadibari-nginx
    ports:
      - "8000:80" # web port
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:latest
    container_name: shadibari-mysql
    restart: always
    environment:
    #   MYSQL_HOST: 127.0.0.1
    #   MYSQL_ROOT_HOST: 127.0.0.1
    #   MYSQL_UNIX_PORT: 3306
    #   MYSQLX_UNIX_PORT: 3306
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: shadibari
      MYSQL_USER: shadibari
      MYSQL_PASSWORD:
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306" # db port
    # extra_hosts:
    #   - localhost:127.0.0.1
    networks:
      - laravel

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: shadibari-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD:
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
