services:
  app:
    build:
      context: ./docker/php
    container_name: shadibari-app
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  web:
    image: nginx:latest
    container_name: shadibari-nginx
    ports:
      - "8000:80" # web port
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: shadibari-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shadibari
      MYSQL_USER: shadibari
      MYSQL_PASSWORD: shadibari
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306" # db port
    networks:
      - laravel

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: shadibari-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel

volumes:
  db-data:

networks:
  laravel:
